### PR TITLE
Add Firefox support

### PR DESCRIPTION
**Pull request by cnnrhill**
Hi, this adds Firefox support to scroblr (#30). `grunt build` and `grunt release` create a .xpi file which can be installed in Firefox. Tested on Firefox 38+.

### CODE REVIEW

**Comment by cgravolet** [comment]
This is cool, thanks for contributing. Will merge it later this week after a quick fix to another plugin is released.

**Comment by cincodenada** [comment]
Wow, excellent!  I have long hoped this extension would get a Firefox version, and happened to look at the GitHub and notice the merge commit.  Cloned, built, and now scrobbling from Pandora flawlessly.  Thanks for the good work, @cnnrhill!  You're a saint.  Y'all feel free to ping me if you need help testing things, I'll let you know if I notice any issues.

**Comment by bonyboy** [comment]
@cincodenada How did you build the app to install as an add-on for Firefox?

**Comment by cincodenada** [comment]
@bonyboy I'm pretty sure I just followed the [guide on the wiki](https://github.com/cgravolet/scroblr/wiki/Setting-Up-Your-Development-Environment), I don't recall having to do anything funny.  Until it's official and such, you'll have to twiddle with your Firefox settings to allow unsigned extensions though.

**Comment by bonyboy** [comment]
Oh I see.  Thanks for showing that to me!

**Comment by hans-juergen** [comment]
OK, so maybe this should be mentioned on the homepage as well, i.e. scroblr also supports Firefox now? ;-) And probably this open issue can be closed then: https://github.com/cgravolet/scroblr/issues/30

Just to make sure, is this using the new WebExtensions API in Firefox already? As far as I know, adding Chrome-like extensions to Firefox is possible in brand-new version 48 now, see also this [FAQ](https://wiki.mozilla.org/WebExtensions/FAQ) and [How-To](http://www.ghacks.net/2016/05/23/install-google-chrome-extensions-firefox/).

**Comment by num4rk** [comment]
@cgravolet Whether there is a possibility of addition this extension to the official Firefox add-ons list?
Otherwise, users have to install it as an unsigned extension manually, as far as i understand.

**Comment by num4rk** [comment]
For those who want to install the unsigned extension, mention that [you can not do this in current stable Release of Firefox](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users).
Even with the xpinstall.signatures.required option turned "false".
You'll have to switch to ESR build or developers / beta versions.

[https://wiki.mozilla.org/Add-ons/Extension_Signing](https://wiki.mozilla.org/Add-ons/Extension_Signing)

**Comment by SyntaxErrol** [comment]
Oh man. Getting this to [AMO](https://addons.mozilla.org/en-US/firefox/) where regular users could install it would be killer.

**Comment by electron0zero** [comment]
any updates on when it will be available on AMO?

**Pull request merged**
